name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - ydata-profiling
  - hydra-core
  - matplotlib
  - pandas
  - pip
  - scikit-learn
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
